-- MySQL Script generated by MySQL Workbench
-- 12/23/20 13:53:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app-base
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `app-base` ;

-- -----------------------------------------------------
-- Schema app-base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app-base` DEFAULT CHARACTER SET utf8 ;
USE `app-base` ;

-- -----------------------------------------------------
-- Table `app-base`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app-base`.`roles` ;

CREATE TABLE IF NOT EXISTS `app-base`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app-base`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app-base`.`users` ;

CREATE TABLE IF NOT EXISTS `app-base`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `member_num` INT(11) NULL DEFAULT 0,
  `password` VARCHAR(100) NOT NULL,
  `active` TINYINT(4) NULL DEFAULT '1',  
  `attempts` TINYINT(1) NULL DEFAULT 0,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_UNIQUE` (`username` ASC),
  INDEX `fk_users_roles_idx` (`role_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `app-base`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app-base`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app-base`.`permissions` ;

CREATE TABLE IF NOT EXISTS `app-base`.`permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app-base`.`role_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app-base`.`role_has_permission` ;

CREATE TABLE IF NOT EXISTS `app-base`.`role_has_permission` (
  `permissions_id` INT(11) NOT NULL,
  `roles_id` INT(11) NOT NULL,
  `reading` TINYINT(1) NULL DEFAULT 0,
  `writing` TINYINT(1) NULL DEFAULT 0,
  INDEX `fk_role_has_permission_permissions1_idx` (`permissions_id` ASC),
  INDEX `fk_role_has_permission_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_role_has_permission_permissions1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `app-base`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `app-base`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `app-base`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `app-base`;
INSERT INTO `app-base`.`roles` (`id`, `name`) VALUES (DEFAULT, 'Administrador');
INSERT INTO `app-base`.`roles` (`id`, `name`) VALUES (DEFAULT, 'Usuario');
INSERT INTO `app-base`.`roles` (`id`, `name`) VALUES (DEFAULT, 'Invitado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `app-base`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `app-base`;
INSERT INTO `app-base`.`users` (`id`, `name`, `lastname`, `email`, `username`, `password`, `active`, `role_id`) VALUES (DEFAULT, 'Administrador', '', 'jmddesarrollo@gmail.com', 'admin', '$2b$10$1WuyQJGknupSkv6SzRloK.EwvXsd3AHprSj5P39zq4PXk1u5jtAty', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `app-base`.`permissions`
-- -----------------------------------------------------
START TRANSACTION;
USE `app-base`;
INSERT INTO `app-base`.`permissions` (`id`, `name`, `detail`) VALUES (DEFAULT, 'permissions_manager', 'Gestión de permisos');
INSERT INTO `app-base`.`permissions` (`id`, `name`, `detail`) VALUES (DEFAULT, 'users_manager', 'Gestión de usuarios');

COMMIT;


-- -----------------------------------------------------
-- Data for table `app-base`.`role_has_permission`
-- -----------------------------------------------------
START TRANSACTION;
USE `app-base`;
INSERT INTO `app-base`.`role_has_permission` (`permissions_id`, `roles_id`, `reading`, `writing`) VALUES ('1', '1', '1', '1');
INSERT INTO `app-base`.`role_has_permission` (`permissions_id`, `roles_id`, `reading`, `writing`) VALUES ('2', '1', '1', '1');

COMMIT;
